env:
  env_id: InvertedPendulumEnv-v0
  model_name: InvPend_0
  w_e: 0
  w_q1: 5
  w_q2: 0.1
  w_r: 1
  w_t: 30
  w_c: 0
  init_pos: 3.1415
  energy_obs: false
  random_init: false
  frame_skip: 10
train:
  n_timesteps: 3000000
  batch_size: 512
  gamma: 0.98
  learning_rate: 0.00025
  device: cuda:1
  seed: 1
