# config.yaml
env:
    env_id: 'InvertedPendulumEnv-v0'
    model_name: 'InvPend_0'
    w_e: 500
    w_q1: 5
    w_q2: 0.1
    w_r: 1
    w_t: 30
    w_c: 5
    init_pos: 3.1415
    energy_obs: True


train:
    n_timesteps: 3000000
    batch_size: 512
    gamma: 0.98
    learning_rate: 2.5e-4
    device: 'cuda:1'