# config.yaml
env:
    env_id: 'InvertedPendulumEnv-v0'
    model_name: 'InvPend'
    w_q1: 5
    w_q2: 0.1
    w_r: 1
    init_pos: 3.1415
    frame_skip: 10
    reward_scaling: True
    max_episode_steps: 2000
    discrete_action: True


train:
    n_timesteps: 3000000
    batch_size: 256
    gamma: 0.98
    learning_rate: 0.0003
    device: 'cuda:1'
    seed: 1
    use_sde: False
    ent_coef: 0